In [1]:
import pymeshlab
import os
ms = pymeshlab.MeshSet()

In [5]:
ms.load_new_mesh('/home/shuyumo/research/GAO/dataset/100013/textured_objs/original-11.obj')
ms.save_current_mesh('output/convex_hull.off')
os.system("cp -r output /mnt/d/Research/output")

0

In [2]:
import numpy as np

from pathlib import Path
cloudpoint = np.load('/home/shuyumo/research/GAO/point2sdf/output/pointcloud/original-2.npz')
points = cloudpoint['points']
normal = cloudpoint['normals']
loc    = cloudpoint['loc']
scale  = cloudpoint['scale']
print(points, type(points), points.shape)
print(normal, type(normal), normal.shape)
print(loc,    type(loc),   loc.shape)
print(scale,    type(scale),   scale.shape)

[[ 0.443    0.1293   0.242  ]
 [ 0.1442   0.2013   0.463  ]
 [-0.3906   0.05914 -0.3147 ]
 ...
 [-0.07416 -0.0431   0.2534 ]
 [-0.4045   0.0943  -0.2424 ]
 [-0.331    0.0108   0.311  ]] <class 'numpy.ndarray'> (10000, 3)
[[ 0.8545   -0.01531   0.5195  ]
 [-0.1876   -0.1155   -0.9756  ]
 [-0.766     0.035    -0.6416  ]
 ...
 [-0.3523    0.0655    0.9336  ]
 [ 0.869     0.014305  0.4941  ]
 [ 0.02219  -0.9995    0.00857 ]] <class 'numpy.ndarray'> (10000, 3)
[-0.07502   -0.6697445 -0.017568 ] <class 'numpy.ndarray'> (3,)
0.08655 <class 'numpy.ndarray'> ()


In [3]:
import numpy as np

from pathlib import Path
samplepoint = np.load('/home/shuyumo/research/GAO/point2sdf/output/point/original-2.npz')
print(samplepoint)
points = samplepoint['points']
occ    = samplepoint['occupancies']
loc    = samplepoint['loc']
scale  = samplepoint['scale']
print(points, type(points), points.shape)
print(occ, type(occ), occ.shape)
for idx, d in enumerate(occ):
    print(idx, d)
print(loc,    type(loc),   loc.shape)
print(scale,    type(scale),   scale.shape)

NpzFile '/home/shuyumo/research/GAO/point2sdf/output/point/original-2.npz' with keys: points, occupancies, loc, scale
[[ 1.371e-01  2.131e-01  3.779e-01]
 [ 3.679e-01 -4.604e-01 -3.909e-02]
 [ 4.619e-01 -2.169e-01 -5.368e-02]
 ...
 [ 1.981e-01  1.068e-02  1.213e-01]
 [-4.270e-01  1.708e-03  2.939e-01]
 [-1.719e-01 -3.219e-04 -4.553e-02]] <class 'numpy.ndarray'> (10000, 3)
[  0   0 128 ...   6   0 212] <class 'numpy.ndarray'> (1250,)
0 0
1 0
2 128
3 1
4 4
5 128
6 128
7 0
8 0
9 0
10 4
11 0
12 0
13 0
14 0
15 2
16 0
17 66
18 0
19 0
20 0
21 0
22 0
23 0
24 0
25 0
26 0
27 0
28 0
29 0
30 0
31 0
32 0
33 0
34 0
35 0
36 0
37 64
38 0
39 4
40 0
41 0
42 0
43 0
44 32
45 0
46 0
47 8
48 64
49 0
50 0
51 0
52 0
53 0
54 0
55 0
56 0
57 0
58 0
59 2
60 0
61 0
62 0
63 0
64 0
65 128
66 0
67 128
68 160
69 0
70 0
71 0
72 8
73 2
74 16
75 64
76 0
77 32
78 8
79 0
80 0
81 0
82 0
83 16
84 0
85 0
86 4
87 0
88 0
89 0
90 0
91 0
92 0
93 2
94 0
95 0
96 0
97 128
98 0
99 0
100 0
101 96
102 0
103 0
104 0
105 32
106 4
107 0
1