In [4]:
import pymeshlab
import os
ms = pymeshlab.MeshSet()

In [5]:
ms.load_new_mesh('/home/shuyumo/research/GAO/dataset/100013/textured_objs/original-11.obj')
ms.save_current_mesh('output/convex_hull.off')
os.system("cp -r output /mnt/d/Research/output")

0

In [5]:
import numpy as np

from pathlib import Path
cloudpoint = np.load('/home/shuyumo/research/GAO/point2sdf/output/pointcloud/original-2.npz')
points = cloudpoint['points']
normal = cloudpoint['normals']
loc    = cloudpoint['loc']
scale  = cloudpoint['scale']
print(points, type(points), points.shape)
print(normal, type(normal), normal.shape)
print(loc,    type(loc),   loc.shape)
print(scale,    type(scale),   scale.shape)

[[-0.3806    0.01117  -0.0605  ]
 [ 0.425     0.1401    0.2034  ]
 [ 0.2473    0.2155    0.4243  ]
 ...
 [-0.1991    0.1327    0.4329  ]
 [-0.04477   0.011215  0.3782  ]
 [-0.001704 -0.2212    0.2512  ]] <class 'numpy.ndarray'> (100000, 3)
[[-0.00454 -1.       0.01956]
 [-0.8936   0.0638  -0.4448 ]
 [-0.45     0.805   -0.3862 ]
 ...
 [ 0.1244   0.1702  -0.9775 ]
 [-0.00833 -0.998    0.05978]
 [ 0.01089 -0.995    0.09595]] <class 'numpy.ndarray'> (100000, 3)
[-0.07502   -0.6697445 -0.017568 ] <class 'numpy.ndarray'> (3,)
0.08655 <class 'numpy.ndarray'> ()


In [9]:
import numpy as np

from pathlib import Path
samplepoint = np.load('/home/shuyumo/research/GAO/point2sdf/output/point/original-2.npz')
print(samplepoint)
points = samplepoint['points']
occ    = samplepoint['occupancies']
loc    = samplepoint['loc']
scale  = samplepoint['scale']
print(points, type(points), points.shape)
print(occ, type(occ), occ.shape)
for idx, d in enumerate(occ):
    print(idx, d)
print(loc,    type(loc),   loc.shape)
print(scale,    type(scale),   scale.shape)

NpzFile '/home/shuyumo/research/GAO/point2sdf/output/point/original-2.npz' with keys: points, occupancies, loc, scale
[[ 0.0583  -0.05093  0.4734 ]
 [ 0.04303  0.404   -0.0713 ]
 [-0.3723  -0.5303   0.3706 ]
 ...
 [ 0.268   -0.376   -0.4092 ]
 [ 0.2524   0.01756 -0.3142 ]
 [ 0.521    0.1813  -0.0718 ]] <class 'numpy.ndarray'> (100000, 3)
[0 0 0 ... 0 0 0] <class 'numpy.ndarray'> (12500,)
[-0.07502   -0.6697445 -0.017568 ] <class 'numpy.ndarray'> (3,)
0.08655 <class 'numpy.ndarray'> ()
